Repository hmcts/sptribs-frontend, pull requests merged in 2022-12, with the labels that each got.

#217 Feat/st 296
  sonar-project.properties
  src/main/app/case/CaseApi.ts
  src/main/app/controller/GetController.ts
  src/main/public/main-dev.js
  src/main/resources/upload-appeal-form/translation.json
  src/main/resources/upload-your-documents/translation.json
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/edge-case/representation/RepresentationPostController.test.ts
  src/main/steps/edge-case/representation/representationPostController.ts
  src/main/steps/edge-case/upload-appeal-form/content.test.ts
  src/main/steps/edge-case/upload-appeal-form/content.ts
  src/main/steps/edge-case/upload-appeal-form/template.njk
  src/main/steps/edge-case/upload-appeal-form/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-appeal-form/uploadDocPostController.ts
  src/main/steps/edge-case/upload-your-documents/template.njk
  src/main/steps/urls.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-217

#224 ST-299 Implement Check your answers
  src/main/app/case/case.ts
  src/main/app/controller/GetController.ts
  src/main/resources/check-your-answers/translation.json
  src/main/steps/common/common.content.ts
  src/main/steps/edge-case/check-your-answers/content.test.ts
  src/main/steps/edge-case/check-your-answers/content.ts
  src/main/steps/edge-case/check-your-answers/form.njk
  src/main/steps/edge-case/check-your-answers/template.njk
  src/main/steps/edge-case/check-your-answers/utils.test.ts
  src/main/steps/edge-case/check-your-answers/utils.ts
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/edge-case/upload-other-information/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-other-information/uploadDocPostController.ts
  src/test/unit/utils/mockUserCase.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-224

#226 Confirmation screen
  src/main/resources/application-submitted/translation.json
  src/main/steps/edge-case/application-submitted/content.test.ts
  src/main/steps/edge-case/application-submitted/content.ts
  src/main/steps/edge-case/application-submitted/template.njk
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-226

#227 ST-298 Do not error if no docs uploaded
  src/main/resources/upload-other-information/translation.json
  src/main/steps/edge-case/check-your-answers/utils.ts
  src/main/steps/edge-case/upload-other-information/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-other-information/uploadDocPostController.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-227

#232 Changed service name to Appeal to the First-tier Tribunal
  src/main/resources/application-submitted/translation.json
  src/main/resources/check-your-answers/translation.json
  src/main/resources/representation-qualified/translation.json
  src/main/resources/representation/translation.json
  src/main/resources/representative-details/translation.json
  src/main/resources/subject-contact-details/translation.json
  src/main/resources/subject-details/translation.json
  src/main/resources/upload-appeal-form/translation.json
  src/main/resources/upload-other-information/translation.json
  src/main/resources/upload-supporting-documents/translation.json
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-232

#234 Feat/st 298 button colour and text
  config/default.yaml
  src/main/assets/scss/main.scss
  src/main/public/main-dev.css
  src/main/resources/upload-appeal-form/translation.json
  src/main/resources/upload-other-information/translation.json
  src/main/resources/upload-supporting-documents/translation.json
  src/main/steps/edge-case/upload-appeal-form/template.njk
  src/main/steps/edge-case/upload-other-information/template.njk
  src/main/steps/edge-case/upload-other-information/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-supporting-documents/template.njk
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-234
