Repository hmcts/sptribs-frontend, pull requests merged in 2022-11, with the labels that each got.

#180 ST-806 - Add content type and tags to secret
  .gitignore
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/variables.tf
Labels: add-or-update, ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-180

#201 adding ST-293 change
  charts/sptribs-frontend/values.yaml
  sonar-project.properties
  src/main/app/case/case.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/modules/oidc/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/public/main-dev.js
  src/main/resources/subject-details/translation.json
  src/main/routes/authless/controllers/landing.ts
  src/main/steps/edge-case/contact-details/content.test.ts
  src/main/steps/edge-case/contact-details/content.ts
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/edge-case/full-name/content.test.ts
  src/main/steps/edge-case/full-name/content.ts
  src/main/steps/edge-case/full-name/template.njk
  src/main/steps/edge-case/subject-details/content.test.ts
  src/main/steps/edge-case/subject-details/content.ts
  src/main/steps/edge-case/subject-details/template.njk
  src/main/steps/edge-case/user-role/content.test.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/index.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/DateOfBirth.page.js
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-201

#203 Feat/ST-328
  src/main/app/case/CaseApi.ts
  src/main/app/case/case.ts
  src/main/app/form/parser.ts
  src/main/public/main-dev.js
  src/main/resources/email-address/translation.json
  src/main/resources/subject-contact-details/translation.json
  src/main/steps/edge-case/check-your-answers/utils.test.ts
  src/main/steps/edge-case/check-your-answers/utils.ts
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/edge-case/email-address/content.test.ts
  src/main/steps/edge-case/subject-contact-details/content.test.ts
  src/main/steps/edge-case/subject-contact-details/content.ts
  src/main/steps/edge-case/subject-contact-details/template.njk
  src/main/steps/urls.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-203

#205 ST-556 Add representation qualified page
  src/main/app/case/CaseApi.ts
  src/main/app/case/case.ts
  src/main/public/main-dev.js
  src/main/resources/representation-qualified/translation.json
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/edge-case/representation-qualified/content.test.ts
  src/main/steps/edge-case/representation-qualified/content.ts
  src/main/steps/edge-case/representation/RepresentationPostController.test.ts
  src/main/steps/edge-case/representation/representationPostController.ts
  src/main/steps/urls.ts
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-205

#206 Added new screen for representative's contact details
  src/main/public/assets/images/govuk-mask-icon.svg
  src/main/public/main-dev.js
  src/main/resources/representative-details/translation.json
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/edge-case/representative-details/content.test.ts
  src/main/steps/edge-case/representative-details/content.ts
  src/main/steps/edge-case/representative-details/template.njk
  src/main/steps/urls.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-206

#208 ST-556 Fix wrong field name for error text
  src/main/resources/representation-qualified/translation.json
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-208

#207 implemented review comments
  src/main/public/main-dev.js
  src/main/resources/representative-details/translation.json
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-207

#216 ST-328 Auto check the checkbox if previously checked
  src/main/steps/edge-case/subject-contact-details/content.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-216
