Repository hmcts/sptribs-frontend, pull requests merged in 2023-12, with the labels that each got.

#577 ST-1496: Enable fortify in nightly pipelines
  Jenkinsfile_nightly
  package.json
  src/test/java/.gitignore
  src/test/java/build.gradle
  src/test/java/config/fortify-client.properties
  src/test/java/gradle/wrapper/gradle-wrapper.jar
  src/test/java/gradle/wrapper/gradle-wrapper.properties
  src/test/java/gradlew
  src/test/java/gradlew.bat
  src/test/java/settings.gradle
  yarn-error.log
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-577

#576 DTSSTCI-76 : Removing Duplicate config
  config/development.yaml
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-576

#571 DTSSTCI-72
  src/main/modules/helmet/index.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-571

#578 DTSSTCI 91
  .husky/pre-commit
  .lintstagedrc.js
  README.md
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-578

#575 DTSSTCI 60
  jest.a11y.config.js
  jest.smoke.config.js
  package.json
  src/test/e2e/tests/smoke_test.js
  src/test/smoke/smoke.ts
  src/test/tests/smoke_test.js
  src/test/tsconfig.json
  yarn.lock
Labels: add-or-update, ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-575

#579 ST-1700: Fix docker related fortify issues
  Dockerfile
Labels: ns:sptribs, prd:sptribs, keep-helm, enable_keep_helm, rel:sptribs-frontend-pr-579

#572 ST-1475
  src/main/modules/session/index.test.ts
  src/main/modules/session/index.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-572

#584 Change join to use new line instead of html
  src/main/steps/edge-case/check-your-answers/utils.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-584

#583 ST-1698: Fix PCQ toggle
  charts/sptribs-frontend/values.preview.template.yaml
  config/default.yaml
  config/development.yaml
  src/main/steps/edge-case/equality/get.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-583
