Repository hmcts/sptribs-frontend, pull requests merged in 2023-09, with the labels that each got.

#436 Get request change
  src/test/e2e/tests/smoke_test.js
  src/test/tests/smoke_test.js
  yarn-audit-known-issues
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-436

#440 St 1189
  codecept.conf.js
  src/test/e2e/pages/CheckYourAnswers.page.js
  src/test/e2e/pages/Representation.page.js
  src/test/e2e/pages/RepresentationQualified.page.js
  src/test/e2e/pages/RepresentativeDetails.page.js
  src/test/e2e/pages/SubjectContactDetails.page.js
  src/test/e2e/pages/SubjectDetails.page.js
  src/test/e2e/pages/UploadAppealForm.page.js
  src/test/e2e/pages/UploadOtherInformation.page.js
  src/test/e2e/pages/UploadSupportingDocuments.page.js
  src/test/e2e/pages/login.page.js
  src/test/e2e/tests/1_SubmitApplication_test.js
  src/test/e2e/tests/BackButton_test.js
  src/test/e2e/tests/ErrorTriggers_test.js
  yarn-audit-known-issues
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-440

#441 CVE Suppression updated to fix build issue
  yarn-audit-known-issues
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-441

#443 Fixed renovate configuration
  .github/renovate.json
  renovate.json
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-443
