Repository hmcts/sptribs-frontend, pull requests merged in 2023-07, with the labels that each got.

#393 ST-1442-node upgrade
  package.json
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-393

#400 ST-1507-refactoring
  src/main/app/controller/GetController.ts
  src/main/steps/edge-case/upload-appeal-form/uploadDocPostController.ts
  src/main/steps/edge-case/upload-other-information/uploadDocPostController.ts
  src/main/steps/edge-case/upload-supporting-documents/uploadDocPostController.ts
  yarn-audit-known-issues
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-400

#390 change to cater pcq is down
  src/main/steps/edge-case/equality/get.ts
Labels: ns:sptribs, prd:sptribs, keep-helm, rel:sptribs-frontend-pr-390

#406 ST-1367 : fixed label
  src/main/resources/check-your-answers/translation.json
Labels: ns:sptribs, prd:sptribs, keep-helm, rel:sptribs-frontend-pr-406
