Repository hmcts/sptribs-frontend, pull requests merged in 2023-04, with the labels that each got.

#270 ST-1032 Add Google Tag Manager
  Jenkinsfile_CNP
  charts/sptribs-frontend/Chart.yaml
  config/default.yaml
  src/main/steps/common/page.njk
  src/main/steps/common/webpack/gtm-noscript.njk
  src/main/steps/common/webpack/gtm-script.njk
  yarn-audit-known-issues
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-270

#276 ST-930 , improve Internal error page
  src/main/steps/error/content.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-276

#278 ST-930 , update error message
  src/main/steps/error/content.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-278

#282 ST-931 Initial implementation of PCQ integration
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/sptribs-frontend/Chart.yaml
  charts/sptribs-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app/case/CaseApi.ts
  src/main/app/case/case.ts
  src/main/modules/properties-volume/index.ts
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/edge-case/equality/PcqParameters.ts
  src/main/steps/edge-case/equality/content.ts
  src/main/steps/edge-case/equality/createToken.test.ts
  src/main/steps/edge-case/equality/createToken.ts
  src/main/steps/edge-case/equality/get.test.ts
  src/main/steps/edge-case/equality/get.ts
  src/main/steps/edge-case/upload-other-information/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-other-information/uploadDocPostController.ts
  src/main/steps/urls.ts
  yarn-audit-known-issues
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-282

#285 ST-913 Better handling of back link
  config/default.yaml
  src/main/assets/js/go-back.ts
  yarn-audit-known-issues
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-285

#286 ST-931 Do not invoke PCQ if under 16
  src/main/steps/edge-case/equality/get.test.ts
  src/main/steps/edge-case/equality/get.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-286

#287 ST-931 Fix bug where age check was a month out
  src/main/steps/edge-case/equality/get.test.ts
  src/main/steps/edge-case/equality/get.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-287
