Repository hmcts/sptribs-frontend, pull requests merged in 2023-10, with the labels that each got.

#449 FIX: Add httpOnly true config to session cookie
  package.json
  src/main/modules/session/index.test.ts
  src/main/modules/session/index.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-449

#451 1189 reactivate tests
  src/test/e2e/tests/1_SubmitApplication_test.js
  src/test/e2e/tests/BackButton_test.js
  src/test/e2e/tests/ErrorTriggers_test.js
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-451

#452 Migrate redis cache to Basic sku in non-prod env
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: destroy, ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-452

#454 DTSSTCI-12
  charts/sptribs-frontend/Chart.yaml
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-454

#442 Fix for CVEs
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-442

#459 Disabling E2E
  src/test/e2e/tests/1_SubmitApplication_test.js
  src/test/e2e/tests/BackButton_test.js
  src/test/e2e/tests/ErrorTriggers_test.js
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-459

#458 Fixed few warnings reported in yarn lint
  .eslintrc.js
  src/main/app/address/SelectAddressPostControllerBase.test.ts
  src/main/steps/common/components/address-international.test.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-458

#461 Changing default URL
  src/test/e2e/config.js
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-461

#464 disabling E2E's for master pipeline failure
  src/test/e2e/tests/1_SubmitApplication_test.js
  src/test/e2e/tests/BackButton_test.js
  src/test/e2e/tests/ErrorTriggers_test.js
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-464

#463 Fixed babel-traverse versioning issue
  package.json
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-463

#475 Jenkins AAT links update
  Jenkinsfile_CNP
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-475

#478 Reactivating E2E's now master pipeline is working
  src/test/e2e/tests/1_SubmitApplication_test.js
  src/test/e2e/tests/BackButton_test.js
  src/test/e2e/tests/ErrorTriggers_test.js
  src/test/e2e/tests/smoke_test.js
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-478

#455 DTSSTCI-9
  src/main/modules/helmet/index.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-455

#479 DTSSTCI-9
  src/main/modules/helmet/index.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-479
