Repository hmcts/sptribs-frontend, pull requests merged in 2023-11, with the labels that each got.

#524 DTSSTCI-43
  charts/sptribs-frontend/Chart.yaml
  charts/sptribs-frontend/values.preview.template.yaml
  config/default.yaml
  jest.config.js
  package.json
  src/main/app/auth/service/get-service-auth-token.test.ts
  src/main/app/auth/service/get-service-auth-token.ts
  src/main/app/auth/user/oidc.test.ts
  src/main/app/auth/user/oidc.ts
  src/main/app/case/CaseApi.ts
  src/main/modules/health/index.ts
  src/main/modules/session/index.test.ts
  src/main/modules/session/index.ts
  src/main/server.ts
  src/main/steps/edge-case/check-your-answers/checkYourAnswerPostController.ts
  src/main/steps/edge-case/upload-appeal-form/uploadDocPostController.ts
  src/main/steps/edge-case/upload-other-information/uploadDocPostController.ts
  src/main/steps/edge-case/upload-supporting-documents/uploadDocPostController.ts
  yarn.lock
Labels: ns:sptribs, prd:sptribs, keep-helm, rel:sptribs-frontend-pr-524, enable_keep_helm

#537 Remove Special Tribs Case API from dev yaml so when running yarn start:dev it defaults to using default.yaml values
  config/development.yaml
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-537

#453 DTSSTCI-8
  package.json
  src/main/assets/js/cookie.ts
  src/main/public/main-dev.js
  src/main/steps/common/common.content.ts
  src/main/steps/cookie-banner/template.njk
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-453

#544 Remove Dependabot from repo as Renovate is now in use
  .github/dependabot.yml
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-544

#532 St 1189 submission page
  codecept.conf.js
  src/test/e2e/fixtures/content/applicationSubmitted_content.js
  src/test/e2e/pages/CheckYourAnswers.page.js
  src/test/e2e/pages/applicationSubmitted.page.js
  src/test/e2e/tests/1_SubmitApplication_test.js
  src/test/e2e/tests/BackButton_test.js
  src/test/e2e/tests/smoke_test.js
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-532

#545 changes for hiding Welsh Language Toggle
  src/main/routes/authless/views/landing.njk
  src/main/steps/common/page.njk
  src/main/views/template.njk
Labels: ns:sptribs, prd:sptribs, keep-helm, enable_keep_helm, rel:sptribs-frontend-pr-545

#549 ST-1542
  src/test/e2e/pages/CheckYourAnswers.page.js
  src/test/e2e/pages/Representation.page.js
  src/test/e2e/tests/1_SubmitApplication_test.js
  src/test/e2e/tests/BackButton_test.js
  src/test/e2e/tests/ErrorTriggers_test.js
  src/test/e2e/tests/smoke_test.js
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-549

#547 ST-1184 Added functional test for nightly pipeline
  Jenkinsfile_nightly
  src/test/e2e/pages/UploadAppealForm.page.js
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-547

#534 DTSSTCI-64
  src/main/steps/common/form/fields/date.njk
Labels: ns:sptribs, prd:sptribs, keep-helm, enable_keep_helm, rel:sptribs-frontend-pr-534

#552 ST-1184 changed the nightly pipeline configuration in jenkins_nightly file
  Jenkinsfile_nightly
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-552

#553 ST-1184 Added config for nightly pipeline to saucelabs.conf.js file
  Jenkinsfile_nightly
  saucelabs.conf.js
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-553

#555 ST-1184 Added config for nightly pipeline to jenkins_nightly file
  Jenkinsfile_nightly
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-555

#556 ST-1184 changes made in package.json file
  package.json
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-556

#533 DTSSTCI-52
  .gitignore
  src/main/assets/images/favicon.ico
  src/main/assets/images/govuk-apple-touch-icon-152x152.png
  src/main/assets/images/govuk-apple-touch-icon-167x167.png
  src/main/assets/images/govuk-apple-touch-icon-180x180.png
  src/main/assets/images/govuk-apple-touch-icon.png
  src/main/assets/images/govuk-crest-2x.png
  src/main/assets/images/govuk-crest.png
  src/main/assets/images/govuk-logotype-crown.png
  src/main/assets/images/govuk-mask-icon.svg
  src/main/assets/images/govuk-opengraph-image.png
  src/main/assets/js/index.ts
  src/main/assets/js/index_old.ts
  src/main/public/assets/fonts/bold-affa96571d-v2.woff
  src/main/public/assets/fonts/bold-b542beb274-v2.woff2
  src/main/public/assets/fonts/light-94a07e06a1-v2.woff2
  src/main/public/assets/fonts/light-f591b13f7d-v2.woff
  src/main/public/hmcts-assets/images/hmcts-logotype-crest.svg
  src/main/public/hmcts-assets/images/icon-alert-information.svg
  src/main/public/hmcts-assets/images/icon-alert-success.svg
  src/main/public/hmcts-assets/images/icon-alert-warning.svg
  src/main/public/hmcts-assets/images/icon-arrow-black-down.svg
  src/main/public/hmcts-assets/images/icon-arrow-black-up.svg
  src/main/public/hmcts-assets/images/icon-arrow-white-down.svg
  src/main/public/hmcts-assets/images/icon-arrow-white-up.svg
  src/main/public/hmcts-assets/images/icon-close-cross-black.svg
  src/main/public/hmcts-assets/images/icon-document.png
  src/main/public/hmcts-assets/images/icon-document.svg
  src/main/public/hmcts-assets/images/icon-pagination.svg
  src/main/public/hmcts-assets/images/icon-progress-tick.png
  src/main/public/hmcts-assets/images/icon-progress-tick.svg
  src/main/public/hmcts-assets/images/icon-search-white.svg
  src/main/public/hmcts-assets/images/icon-tag-remove-cross-white.svg
  src/main/public/hmcts-assets/images/icon-tag-remove-cross.svg
  src/main/public/hmcts-assets/images/icon-toggle-plus-minus.svg
  src/main/public/hmcts-assets/images/icon-wysiwyg-bold.svg
  src/main/public/hmcts-assets/images/icon-wysiwyg-italic.svg
  src/main/public/hmcts-assets/images/icon-wysiwyg-ordered-list.svg
  src/main/public/hmcts-assets/images/icon-wysiwyg-underline.svg
  src/main/public/hmcts-assets/images/icon-wysiwyg-unordered-list.svg
  src/main/public/main-dev.css
  src/main/public/main-dev.js
  src/main/routes/authless/views/landing.njk
  src/main/steps/home/get.ts
  src/main/types/govuk-frontend.d.ts
Labels: ns:sptribs, prd:sptribs, keep-helm, enable_keep_helm, rel:sptribs-frontend-pr-533

#554 ST1543
  src/test/e2e/pages/CheckYourAnswers.page.js
  src/test/e2e/pages/UploadOtherInformation.page.js
  src/test/e2e/tests/1_SubmitApplication_test.js
  src/test/e2e/tests/BackButton_test.js
  src/test/e2e/tests/ErrorTriggers_test.js
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-554

#559 ST1544
  src/test/e2e/pages/CheckYourAnswers.page.js
  src/test/e2e/pages/RepresentationQualified.page.js
  src/test/e2e/pages/UploadOtherInformation.page.js
  src/test/e2e/tests/1_SubmitApplication_test.js
  src/test/e2e/tests/BackButton_test.js
  src/test/e2e/tests/ErrorTriggers_test.js
  src/test/e2e/tests/smoke_test.js
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-559

#561 ST-1184 Changed login page details
  package.json
  src/test/e2e/pages/login.page.js
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-561

#560 ST1189
  src/test/e2e/pages/CheckYourAnswers.page.js
  src/test/e2e/pages/LandingPage.js
  src/test/e2e/pages/Representation.page.js
  src/test/e2e/pages/RepresentationQualified.page.js
  src/test/e2e/pages/RepresentativeDetails.page.js
  src/test/e2e/pages/SubjectContactDetails.page.js
  src/test/e2e/pages/SubjectDetails.page.js
  src/test/e2e/pages/UploadAppealForm.page.js
  src/test/e2e/pages/UploadOtherInformation.page.js
  src/test/e2e/pages/UploadSupportingDocuments.page.js
  src/test/e2e/pages/applicationSubmitted.page.js
  src/test/e2e/tests/1_SubmitApplication_test.js
  src/test/e2e/tests/BackButton_test.js
  src/test/e2e/tests/ErrorTriggers_test.js
  src/test/e2e/tests/smoke_test.js
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-560

#564 E2E Playwright conversion
  .gitignore
  codecept.conf.js
  package.json
  playwright.config.ts
  src/test/e2e/helpers/browser_helper.js
  src/test/e2e/helpers/dump_browser_logs_helper.js
  src/test/e2e/helpers/event_listener.js
  src/test/e2e/helpers/hooks_helper.js
  src/test/e2e/pages/CheckYourAnswers.page.js
  src/test/e2e/pages/Representation.page.js
  src/test/e2e/pages/RepresentationQualified.page.js
  src/test/e2e/pages/RepresentativeDetails.page.js
  src/test/e2e/pages/SubjectContactDetails.page.js
  src/test/e2e/pages/SubjectDetails.page.js
  src/test/e2e/pages/UploadAppealForm.page.js
  src/test/e2e/pages/UploadOtherInformation.page.js
  src/test/e2e/pages/UploadSupportingDocuments.page.js
  src/test/e2e/pages/applicationSubmitted.page.js
  src/test/e2e/pages/login.page.js
  src/test/e2e/tests/1_SubmitApplication_test.js
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-564

#567 Adding cross browser capability
  codecept.conf.js
  package.json
  src/test/e2e/tests/1_SubmitApplication_test.js
  src/test/e2e/tests/BackButton_test.js
  src/test/e2e/tests/ErrorTriggers_test.js
  src/test/e2e/tests/smoke_test.js
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-567

#568 Adding mobile device testing
  codecept.conf.js
  package.json
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-568

#569 Worker update
  package.json
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-569

#570 Worker update
  package.json
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-570
