Repository hmcts/sptribs-frontend, pull requests merged in 2023-08, with the labels that each got.

#391 button label change
  src/main/steps/edge-case/application-submitted/template.njk
  src/main/steps/edge-case/equality/get.test.ts
  src/main/steps/edge-case/equality/get.ts
  src/test/e2e/actors/base.js
  yarn-audit-known-issues
Labels: ns:sptribs, prd:sptribs, keep-helm, rel:sptribs-frontend-pr-391

#413 ST-1504 Document size changed
  config/default.yaml
  src/main/steps/edge-case/upload-appeal-form/uploadDocPostController.ts
  src/main/steps/edge-case/upload-other-information/uploadDocPostController.ts
  src/main/steps/edge-case/upload-supporting-documents/uploadDocPostController.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-413

#410 ST-1189 reactivate tests
  codecept.conf.js
  src/test/e2e/fixtures/content/AdditionalDocuments_content.js
  src/test/e2e/fixtures/content/ApplicantName_content.js
  src/test/e2e/fixtures/content/CheckYourAnswers_content.js
  src/test/e2e/fixtures/content/ContactNumber_content.js
  src/test/e2e/fixtures/content/ContactPreferences_content.js
  src/test/e2e/fixtures/content/DetermineRole_content.js
  src/test/e2e/fixtures/content/EmailAddress_content.js
  src/test/e2e/fixtures/content/LandingPage_content.js
  src/test/e2e/fixtures/content/RepresentationQualified_content.js
  src/test/e2e/fixtures/content/Representation_content.js
  src/test/e2e/fixtures/content/RepresentativeDetails_content.js
  src/test/e2e/fixtures/content/StatementOfTruth_content.js
  src/test/e2e/fixtures/content/SubjectContactDetails_content.js
  src/test/e2e/fixtures/content/SubjectDetails_content.js
  src/test/e2e/fixtures/content/UploadAppealForm_content.js
  src/test/e2e/fixtures/content/UploadDocuments_content.js
  src/test/e2e/fixtures/content/UploadOtherInformation_content.js
  src/test/e2e/fixtures/content/UploadSupportingDocuments_content.js
  src/test/e2e/helpers/pa11y_helper.js
  src/test/e2e/pages/AdditionalDocuments.page.js
  src/test/e2e/pages/AddressWithPostCode.page.js
  src/test/e2e/pages/ApplytoApplicant.page.js
  src/test/e2e/pages/CheckYourAnswers.page.js
  src/test/e2e/pages/ContactNumbers.page.js
  src/test/e2e/pages/ContactPreference.page.js
  src/test/e2e/pages/DateOfBirth.page.js
  src/test/e2e/pages/DetermineApplicantRole.page.js
  src/test/e2e/pages/EmailAddress.page.js
  src/test/e2e/pages/LandingPage.js
  src/test/e2e/pages/Representation.page.js
  src/test/e2e/pages/RepresentationQualified.page.js
  src/test/e2e/pages/RepresentativeDetails.page.js
  src/test/e2e/pages/StatementOfTruth.page.js
  src/test/e2e/pages/SubjectContactDetails.page.js
  src/test/e2e/pages/SubjectDetails.page.js
  src/test/e2e/pages/ThankYou.page.js
  src/test/e2e/pages/UploadAppealForm.page.js
  src/test/e2e/pages/UploadDocuments.page.js
  src/test/e2e/pages/UploadOtherInformation.page.js
  src/test/e2e/pages/UploadSupportingDocuments.page.js
  src/test/e2e/pages/login.page.js
  src/test/e2e/tests/SubmitApplication_test.js
  src/test/e2e/tests/smoke_test.js
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-410

#416 St 1189 error journey
  src/test/e2e/config.js
  src/test/e2e/fixtures/content/RepresentationQualified_content.js
  src/test/e2e/fixtures/content/Representation_content.js
  src/test/e2e/fixtures/content/RepresentativeDetails_content.js
  src/test/e2e/fixtures/content/SubjectContactDetails_content.js
  src/test/e2e/fixtures/content/SubjectDetails_content.js
  src/test/e2e/fixtures/content/UploadAppealForm_content.js
  src/test/e2e/fixtures/content/UploadOtherInformation_content.js
  src/test/e2e/fixtures/content/UploadSupportingDocuments_content.js
  src/test/e2e/fixtures/testFiles/mockFile.odt
  src/test/e2e/pages/Representation.page.js
  src/test/e2e/pages/RepresentationQualified.page.js
  src/test/e2e/pages/RepresentativeDetails.page.js
  src/test/e2e/pages/SubjectContactDetails.page.js
  src/test/e2e/pages/SubjectDetails.page.js
  src/test/e2e/pages/UploadAppealForm.page.js
  src/test/e2e/pages/UploadOtherInformation.page.js
  src/test/e2e/pages/UploadSupportingDocuments.page.js
  src/test/e2e/tests/ErrorTriggers_test.js
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-416

#421 Temporary disable due to AAT error
  src/test/e2e/tests/ErrorTriggers_test.js
  src/test/e2e/tests/SubmitApplication_test.js
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-421

#420 ST-1406: DSS Update case url added
  src/main/routes/authless/controllers/updateLanding.ts
  src/main/routes/authless/path.ts
  src/main/routes/authless/routes.ts
  yarn-audit-known-issues
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-420

#418 ST-1475 Changing httpOnly to false and secure to true.
  src/main/modules/session/index.test.ts
  src/main/modules/session/index.ts
Labels: ns:sptribs, prd:sptribs, keep-helm, rel:sptribs-frontend-pr-418

#426 ST-117 Smoke test report configured in JENKINS_CNP file
  Jenkinsfile_CNP
  yarn-audit-known-issues
Labels: ns:sptribs, prd:sptribs, keep-helm, rel:sptribs-frontend-pr-426

#424 ST-1570 Adding renovate config
  renovate.json
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-424

#427 St-1179 smoke test report added for aat
  Jenkinsfile_CNP
Labels: ns:sptribs, prd:sptribs, keep-helm, rel:sptribs-frontend-pr-427
