Repository hmcts/sptribs-frontend, pull requests merged in 2023-06, with the labels that each got.

#336 ST-955
  config/default.yaml
  src/main/resources/upload-other-information/translation.json
  src/main/steps/edge-case/upload-appeal-form/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-other-information/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-supporting-documents/uploadDocPostController.test.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-336

#332 fix depricated config
  Dockerfile
  package.json
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-332

#338 St 955
  config/default.yaml
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-338

#335 Removing debugging Service Auth Token log output
  src/main/app/auth/service/get-service-auth-token.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-335

#344 Preview env - DO NOT MERGE
  charts/sptribs-frontend/values.preview.template.yaml
Labels: ns:sptribs, prd:sptribs, keep-helm, rel:sptribs-frontend-pr-344

#348 ST-1456 update text on contact page
  src/main/public/main-dev.js
  src/main/resources/subject-contact-details/translation.json
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-348

#347 ST-1459-console.log clear
  src/main/app/case/CaseApi.ts
  src/main/app/case/formatter/address.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.ts
  src/main/modules/session/index.ts
  src/main/steps/edge-case/subject-details/content.ts
  src/main/steps/edge-case/upload-appeal-form/uploadDocPostController.ts
  src/main/steps/edge-case/upload-other-information/uploadDocPostController.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-347

#359 Back to master branch of the redis module
  infrastructure/main.tf
Labels: ns:sptribs, prd:sptribs, no-changes, rel:sptribs-frontend-pr-359

#362 ST-1403-unit tests
  src/main/app/case/answers/formatDate.test.ts
  src/main/app/case/case.test.ts
  src/main/app/case/formatter/address.test.ts
  src/main/modules/appinsights/index.test.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-362

#366 ST-1470-CVE fixing
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-366

#363 ST-1448-CVE-Fix-unit-test-refactoring
  src/main/app/case/answers/formatDate.test.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-363

#379 ST-1471 - DSS create draft/submitted state FRONTEND changes
  src/main/app/case/CaseApi.ts
  src/main/app/controller/PostController.ts
  src/main/resources/check-your-answers/translation.json
  src/main/steps/common/constants/apiConstants.ts
  src/main/steps/edge-case/check-your-answers/checkYourAnswerPostController.test.ts
  src/main/steps/edge-case/check-your-answers/checkYourAnswerPostController.ts
Labels: ns:sptribs, prd:sptribs, keep-helm, rel:sptribs-frontend-pr-379

#381 ST-1471 - DSS create draft/submitted state FRONTEND changes
  src/main/app/case/CaseApi.ts
  src/main/app/controller/PostController.ts
  src/main/resources/check-your-answers/translation.json
  src/main/steps/common/constants/apiConstants.ts
  src/main/steps/edge-case/check-your-answers/checkYourAnswerPostController.test.ts
  src/main/steps/edge-case/check-your-answers/checkYourAnswerPostController.ts
  yarn-audit-known-issues
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-381

#386 ST-1475-cookie security/ST-1447-nightly-pipeline
  Jenkinsfile_nightly
  src/main/app/controller/GetController.ts
  src/main/modules/session/index.test.ts
  src/main/modules/session/index.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-386

#387 ST-1475-cookie security
  src/main/app/controller/GetController.ts
  src/main/modules/session/index.test.ts
  src/main/modules/session/index.ts
Labels: ns:sptribs, prd:sptribs, keep-helm, rel:sptribs-frontend-pr-387

#389 ST-1475-cookie security
  src/main/modules/session/index.test.ts
  src/main/modules/session/index.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-389
