Repository hmcts/sptribs-frontend, pull requests merged in 2023-05, with the labels that each got.

#281 Feat/ST-1611_feedback_banner_message and add url to eachpage
  package.json
  src/main/app/auth/user/oidc.test.ts
  src/main/app/auth/user/oidc.ts
  src/main/modules/nunjucks/index.ts
  src/main/public/main-dev.js
  src/main/resources/landing/translation.json
  src/main/routes/authless/views/authless-templates.njk
  src/main/routes/authless/views/landing.njk
  src/main/steps/common/common.content.ts
  src/main/steps/common/page.njk
  src/main/steps/common/template.njk
  src/main/views/macros/csrf.njk
  src/main/views/template.njk
  yarn-audit-known-issues
  yarn-error.log
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-281

#298 Feat/st 1003
  .github/workflows/checks.yml
  .gitignore
  .nvmrc
  .yarn/releases/yarn-3.5.1.cjs
  .yarnrc.yml
  package.json
  src/main/app/auth/user/oidc.test.ts
  src/main/app/auth/user/oidc.ts
  src/main/app/case/case.ts
  src/main/assets/scss/main.scss
  src/main/public/main-dev.css
  src/main/public/main-dev.js
  src/main/steps/edge-case/upload-appeal-form/uploadDocPostController.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-298

#305 St 1004 - fronted dss other info page
  src/main/public/main-dev.js
  src/main/resources/upload-other-information/translation.json
  src/main/steps/edge-case/upload-additional-documents/uploadDocPostController.ts
  src/main/steps/edge-case/upload-appeal-form/uploadDocPostController.ts
  src/main/steps/edge-case/upload-other-information/template.njk
  src/main/steps/edge-case/upload-other-information/uploadDocPostController.ts
  src/main/steps/edge-case/upload-supporting-documents/uploadDocPostController.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-305

#306 Bugfix/st 1368
  config/default.yaml
  sonar-project.properties
  src/main/app/case/CaseApi.ts
  src/main/app/case/case.ts
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.ts
  src/main/modules/health/index.ts
  src/main/modules/timeouts/index.ts
  src/main/public/main-dev.js
  src/main/resources/upload-addtional-documents/translation.json
  src/main/steps/common/constants/apiConstants.ts
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/edge-case/equality/get.test.ts
  src/main/steps/edge-case/equality/get.ts
  src/main/steps/edge-case/upload-additional-documents/content.test.ts
  src/main/steps/edge-case/upload-additional-documents/content.ts
  src/main/steps/edge-case/upload-additional-documents/template.njk
  src/main/steps/edge-case/upload-additional-documents/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-additional-documents/uploadDocPostController.ts
  src/main/steps/edge-case/upload-appeal-form/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-appeal-form/uploadDocPostController.ts
  src/main/steps/edge-case/upload-other-information/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-other-information/uploadDocPostController.ts
  src/main/steps/edge-case/upload-supporting-documents/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-supporting-documents/uploadDocPostController.ts
  src/main/steps/urls.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-306

#307 ST-1363 Fixing issues revealed by pipeline.
  infrastructure/.terraform-version
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: add-or-update, ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-307

#309 idam pr set
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/sptribs-frontend/Chart.yaml
  charts/sptribs-frontend/values.preview.template.yaml
  charts/sptribs-frontend/values.yaml
  config/default.yaml
  infrastructure/main.tf
  src/main/app/auth/user/oidc.test.ts
  src/main/modules/appinsights/index.ts
  src/main/modules/session/index.test.ts
  src/main/modules/session/index.ts
  yarn-error.log
Labels: add-or-update, ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-309, keep-helm

#312 Update main.tf
  infrastructure/main.tf
Labels: destroy

#315 Release 2 QA PR. ** DO NOT MERGE **
  Jenkinsfile_CNP
  README.md
  charts/sptribs-frontend/Chart.yaml
  config/production.yaml
  infrastructure/main.tf
  src/main/app/auth/service/get-service-auth-token.ts
  src/main/modules/health/index.ts
Labels: destroy, ns:sptribs, prd:sptribs, keep-helm, rel:sptribs-frontend-pr-315

#322 St 1349
  charts/sptribs-frontend/Chart.yaml
  charts/sptribs-frontend/values.yaml
  config/custom-environment-variables.yaml
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-322

#324 ST-1384 landing page, routing and redirect
  src/main/routes/authless/path.ts
  src/main/routes/authless/routes.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-324

#325 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-325

#327 Feat/st 1611 feedback banner message. updated submitted page and redirect button
  .nvmrc
  src/main/resources/application-submitted/translation.json
  src/main/resources/landing/translation.json
  src/main/routes/authless/views/authless-templates.njk
  src/main/steps/common/common.content.ts
  src/main/steps/edge-case/application-submitted/content.ts
  src/main/steps/edge-case/application-submitted/template.njk
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-327
