Repository hmcts/sptribs-frontend, pull requests merged in 2024-08, with the labels that each got.

#666 DTSSTCI-821: DAC - Error Suggestion (Submit Case)
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/resources/representative-details/translation.json
  src/main/resources/subject-contact-details/translation.json
  src/main/resources/subject-details/translation.json
  src/main/steps/edge-case/subject-details/content.test.ts
  src/main/steps/edge-case/subject-details/content.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, aat/add-or-update, prod/no-changes, rel:sptribs-frontend-pr-666

#677 DTSSTCI-938
  src/main/steps/edge-case/equality/get.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-677

#675 DTSSTCI-918: Welsh content for Submit case subject email and contact number error messages
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/resources/check-your-answers/translation.json
  src/main/resources/representative-details/translation.json
  src/main/resources/subject-contact-details/translation.json
  src/main/resources/upload-appeal-form/translation.json
  src/main/resources/upload-other-information/translation.json
  src/main/resources/upload-supporting-documents/translation.json
  src/main/steps/common/common.content.ts
  src/main/steps/error/content.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, aat/add-or-update, prod/no-changes, rel:sptribs-frontend-pr-675

#679 DTSSTCI-1009: Fix axios dependency failure
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-679

#659 DTSSTCI-730
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/UploadController.ts
  src/main/app/form/Form.test.ts
  src/main/app/form/parser.test.ts
  src/main/app/form/parser.ts
  src/main/app/form/validation.test.ts
  src/main/resources/check-your-answers/translation.json
  src/main/resources/contact-details/translation.json
  src/main/resources/representation-qualified/translation.json
  src/main/resources/representation/translation.json
  src/main/resources/representative-details/translation.json
  src/main/resources/statement-of-truth/translation.json
  src/main/resources/subject-contact-details/translation.json
  src/main/resources/upload-appeal-form/translation.json
  src/main/resources/upload-other-information/translation.json
  src/main/resources/upload-supporting-documents/translation.json
  src/main/resources/user-role/translation.json
  src/main/steps/common/common.content.ts
  src/main/steps/edge-case/date-of-birth/content.ts
  src/main/steps/edge-case/representative-details/content.test.ts
  src/main/steps/edge-case/representative-details/content.ts
  src/main/steps/edge-case/subject-details/content.ts
  src/main/steps/edge-case/upload-appeal-form/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-other-information/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-supporting-documents/uploadDocPostController.test.ts
  src/main/steps/error/content.ts
  src/main/steps/errorMesages.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-659

#683 DTSSTCI-1041: Fixed axios dependency failure
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-683

#652 DTSSTCI-822: DAC - Redundant Entry (Submit Case)
  src/main/app/case/CaseApi.ts
  src/main/app/case/case.ts
  src/main/app/controller/UploadController.test.ts
  src/main/app/controller/UploadController.ts
  src/main/app/form/Form.ts
  src/main/assets/scss/main.scss
  src/main/resources/check-your-answers/translation.json
  src/main/steps/common/components/address-international.test.ts
  src/main/steps/common/components/address-lookup.test.ts
  src/main/steps/common/components/address-manual.test.ts
  src/main/steps/common/components/address-select.test.ts
  src/main/steps/common/components/common/radios.test.ts
  src/main/steps/common/components/full-name.test.ts
  src/main/steps/common/components/input.test.ts
  src/main/steps/edge-case/address/lookup/content.test.ts
  src/main/steps/edge-case/check-your-answers/content.test.ts
  src/main/steps/edge-case/check-your-answers/utils.ts
  src/main/steps/edge-case/contact-preferences/content.test.ts
  src/main/steps/edge-case/date-of-birth/content.test.ts
  src/main/steps/edge-case/equality/get.test.ts
  src/main/steps/edge-case/equality/get.ts
  src/main/steps/edge-case/representative-details/content.test.ts
  src/main/steps/edge-case/statement-of-truth/content.test.ts
  src/main/steps/edge-case/subject-contact-details/content.test.ts
  src/main/steps/edge-case/subject-details/content.test.ts
  src/main/steps/edge-case/upload-appeal-form/content.test.ts
  src/main/steps/edge-case/upload-appeal-form/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-other-information/content.test.ts
  src/main/steps/edge-case/upload-other-information/content.ts
  src/main/steps/edge-case/upload-other-information/template.njk
  src/main/steps/edge-case/upload-other-information/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-supporting-documents/content.test.ts
  src/main/steps/edge-case/upload-supporting-documents/uploadDocPostController.test.ts
  src/main/steps/edge-case/user-role/content.test.ts
  src/test/unit/utils/mockUserCase.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, aat/add-or-update, prod/no-changes, rel:sptribs-frontend-pr-652

#680 DTSSTCI-1066: Enabled app insights logging in preview
  charts/sptribs-frontend/Chart.yaml
  charts/sptribs-frontend/values.preview.template.yaml
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-680

#678 DTSSTCI-1003: Fix hasOwnProperty issue in prod
  src/main/app/controller/GetController.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-678
