Repository hmcts/sptribs-frontend, pull requests merged in 2024-03, with the labels that each got.

#603 Revert azurem version to attempt to fix update case pipeline
  infrastructure/state.tf
Labels: add-or-update, ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-603

#604 DTSSTCI-557
  charts/sptribs-frontend/Chart.yaml
  charts/sptribs-frontend/values.yaml
  config/default.yaml
  src/main/modules/helmet/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/routes/authless/views/authless-templates.njk
  src/main/steps/common/page.njk
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-604

#607 Bump terraform-provider-azurerm to latest version 3.95.0
  infrastructure/state.tf
Labels: add-or-update, ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-607

#606 DTSSTCI-81
  src/main/resources/cookies/translation.json
  src/main/steps/common/common.content.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-606

#612 DTSSTCI-668: Fix for CVE-2024-28849
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-612

#608 DTSSTCI-104 Special Tribs Frontend - Fix Warnings for Custom Assertion
  .eslintrc.js
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/PostController.test.ts
  src/main/steps/common/components/common/component.test.ts
  src/main/steps/common/components/common/radios.test.ts
  src/main/steps/common/components/input.test.ts
  src/main/steps/common/test/languageAssertions.ts
  src/test/unit/sample.ts
  src/test/unit/utils/languageAssertions.ts
Labels: add-or-update, ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-608

#614 DTSSTCI-396
  charts/sptribs-frontend/Chart.yaml
  charts/sptribs-frontend/values.yaml
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-614

#615 DTSSTCI-396
  charts/sptribs-frontend/Chart.yaml
  charts/sptribs-frontend/values.yaml
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-615

#620 DTSSTCI-686: Fix for CVE-2024-29041
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-620

#619 Dtsstci 103 - Complete Unit Tests in Special Tribs Frontend: Get and Post Controllers
  config/test.yaml
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/form/Form.test.ts
  src/main/steps/common/components/common/renderSubFields.test.ts
  src/test/unit/utils/defaultViewArgs.ts
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-619
