Repository hmcts/sptribs-frontend, pull requests merged in 2024-04, with the labels that each got.

#621 DTSSTCI-675
  src/main/app/controller/GetController.ts
  src/main/modules/oidc/index.ts
  src/main/steps/common/common.content.ts
  src/main/steps/edge-case/check-your-answers/content.test.ts
  src/main/steps/edge-case/cookies/template.njk
  src/main/steps/timed-out/get.test.ts
  src/main/steps/timed-out/get.ts
  src/main/steps/url-utils.test.ts
  src/main/steps/url-utils.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-621

#622 DTSSTCI-710
  src/main/app/controller/UploadController.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-622

#623 DTSSTCI-711
  charts/sptribs-frontend/Chart.yaml
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-623

#625 DTSSTCI-667
  src/main/app/auth/user/oidc.test.ts
  src/main/app/auth/user/oidc.ts
  src/main/app/case/CaseApi.test.ts
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.ts
  src/main/app/controller/UploadController.ts
  src/main/modules/oidc/index.ts
  src/main/steps/edge-case/check-your-answers/checkYourAnswerPostController.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-625

#626 DTSSTCI-74
  package.json
  webpack.config.js
  yarn.lock
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-626

#627 DTSSTCI-718
  src/main/resources/landing/translation.json
  src/main/routes/authless/views/landing.njk
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-627

#633 Resolve downstream cve issue with formidable in hmcts/nodejs-logging package
  package.json
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-633

#630 DTSSTCI-720
  src/main/steps/edge-case/check-your-answers/form.njk
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, aat/add-or-update, rel:sptribs-frontend-pr-630

#635 DTSSTCI-724
  src/main/resources/representation-qualified/translation.json
  src/main/resources/representation/translation.json
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-635

#632 DTSSTCI-758
  package.json
  src/main/server.ts
  yarn.lock
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-632

#638 DTSSTCI-744
  src/main/steps/privacy-policy/content.test.ts
  src/main/steps/privacy-policy/content.ts
  src/main/steps/privacy-policy/template.njk
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-638

#637 DTSSTCI-754
  config/default.yaml
  config/development.yaml
  src/main/app/controller/UploadController.test.ts
  src/main/app/controller/UploadController.ts
  src/main/modules/fileupload/index.test.ts
  src/main/modules/fileupload/index.ts
  src/main/resources/upload-appeal-form/translation.json
  src/main/resources/upload-other-information/translation.json
  src/main/resources/upload-supporting-documents/translation.json
  src/main/steps/edge-case/upload-appeal-form/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-other-information/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-supporting-documents/uploadDocPostController.test.ts
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-637
