Repository hmcts/sptribs-frontend, pull requests merged in 2025-07, with the labels that each got.

#803 Remove jitpack dependency
  src/test/java/build.gradle
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-803

#806 Fix fortify
  src/test/java/build.gradle
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-806

#812 Update superagent to 10.2.2+
  package.json
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-812

#822 Upgrade express-session version
  package.json
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-822

#807 DTSSTCI-1072: SpTribs Frontend - Inline error messaging not showing
  src/main/steps/edge-case/upload-other-information/template.njk
Labels: ns:sptribs, prd:sptribs, enable_keep_helm, rel:sptribs-frontend-pr-807

#829 Update axios version and remove unneeded suppression
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sptribs, prd:sptribs, rel:sptribs-frontend-pr-829
